name: mockproject
version: '${version}'

main: com.minzoid.mockproject.MockProject
api-version: '1.21.4'
load: POSTWORLD
folia-supported: true
commands:
  checkdata:
    description: Check the loaded data from the database
    usage: /<command>
